import pandas as pd
import numpy as np
import glob
from snakemake.utils import validate
from snakemake.utils import min_version
import os
import re
import yaml
import argparse
import math
import importlib.util

# ############ SETUP ##############################

configfile: "../config/config1104.yaml"

workdir: config["general"]["work_dir"]

df = pd.read_csv(config["general"]["SampleSheet"], sep = ',', skiprows=13)
SAMPLES = list(df.iloc[:,1])
samples = SAMPLES

file_ending = ".realigned.bam"
input_bam = {}
for sample in samples:
    input_bam[sample] = ''.join([config["general"]["work_dir"], "mapped/", sample, file_ending])


# ############ INCLUDES ##############################
# include helper functions
include: "../umi-demultiplex/rules/demux.smk"

include: "../umi-preprocessing/rules/resources.smk"
include: "../umi-preprocessing/rules/mapping.smk"
include: "../umi-preprocessing/rules/qc.smk"
include: "../umi-preprocessing/rules/tools.smk"

include: "../umi-variantcalling/rules/io.snk"
include: "../umi-variantcalling/rules/utils.snk"
include: "../umi-variantcalling/rules/resources.smk"
include: "../umi-variantcalling/rules/variantcalling.snk"
include: "../umi-variantcalling/rules/annotate.snk"
include: "../umi-variantcalling/rules/filterbam.snk"


# specified wildcards have to match the regex
wildcard_constraints:
    # eg sample cannot contain _ or / to prevent ambiguous wildcards
    sample = "[^/.]+",
    read = "[^_/.]+",
    read_or_index = "[^_/.]+",
    filter = "filter[0-9]+"
    # folder = "^((?!filter).)*$"


# ############## MASTER RULE ##############################################

rule all:
    input:
        expand("unmapped/{sample}.unmapped.bam", sample=SAMPLES),
        expand("mapped/{sample}.realigned.bam", sample=SAMPLES),
        # "qc/multiqc_reads.html",
        # "qc/multiqc_alignments.html",
        # "filter/variantcalls.csv"
        # expand("vardict/{sample}.vcf", sample = samples),

###########################################################################
