import os
import re
import yaml
import argparse
import math
import importlib.util
# import pysam

# ############ SETUP ##############################

configfile: "../config/config1557.yaml"

workdir: config["general"]["work_dir"] + "variantcalling/"

samples = os.listdir(config["general"]["work_dir"] + "demux/mapped")
samples = list(filter(lambda x:'.realigned.bam' in x, samples))
samples = list(filter(lambda x:'.bai' not in x, samples)) ### ROBERT: otherwise index files stay in Samples
samples = [s.replace('.realigned.bam', '') for s in samples]

list(filter(lambda x:'.bai' in x, samples))

file_ending = ".realigned.bam"
input_bam = {}
for sample in samples:
    input_bam[sample] = ''.join([config["general"]["work_dir"], "demux/mapped/", sample, file_ending])


# ############ INCLUDES ##############################
# include helper functions
include: "rules/io.snk"
include: "rules/utils.snk"
include: "../config/rules/resources.smk"

include: "rules/variantcalling.snk"
include: "rules/annotate.snk"
include: "rules/filterbam.snk"


# specified wildcards have to match the regex
wildcard_constraints:
    # eg sample cannot contain _ or / to prevent ambiguous wildcards
    sample = "[^/.]+",
    read = "[^_/.]+",
    read_or_index = "[^_/.]+",
    filter = "filter[0-9]+"
    # folder = "^((?!filter).)*$"


# ############## MASTER RULE ##############################################

rule all:
    input:
        expand("vardict/{sample}.vcf", sample = samples),
        "filter/variantcalls.csv"
        # expand("table/{sample}.edit.csv", sample = samples),
        # "vardict/AML-108.vcf",
        # expand("vardict/{sample}.vcf", sample = samples),

###########################################################################
