# ==============================================================================
# Snakemake workflow: Preprocessing of Illumina sequencing data 
#                     containing unique molecular identifiers (UMIs)
#
# Author: Raphael Hablesreiter (raphael.hablesreiter@charite.de)
#
# Description:
# Snakemake implementation of IDT analysis guidlines "Demultiplexing Illumina 
# sequencing data containing unique molecular identifiers (UMIs)".
# ==============================================================================

# ==============================================================================
# Initialization of workflow
# ==============================================================================

import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

min_version("5.7.1")

# configfile: "config_stroke.yaml"
# configfile: "config/config1413_aml.yaml"
# configfile: "config1156.yaml"
configfile: "../config/config1557.yaml"
validate(config, schema="schemas/config.schema.yaml")

SAMPLES = os.listdir(config["general"]["work_dir_demux"] +"/unmapped/")
SAMPLES = list(filter(lambda x:'.unmapped.bam' in x, SAMPLES))
SAMPLES = [s.replace('.unmapped.bam', '') for s in SAMPLES]
# SAMPLES = SAMPLES[:30]
# SAMPLES.remove("AML-175_newprep")
# SAMPLES = "4-B7"

workdir: config["general"]["work_dir_demux"]

# ==============================================================================
# Include rules
# ==============================================================================

include: "../config/resources.smk"
include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/tools.smk"

# ==============================================================================
# Results
# ==============================================================================

rule all:
    input:
        # expand("mapped/{sample}.consensusreads.bam", sample=SAMPLES),
        # expand("mapped/{sample}.consensusreads.bam.bai", sample=SAMPLES),
        expand("mapped/{sample}.realigned.bam", sample=SAMPLES),
        expand("mapped/{sample}.realigned.bam.bai", sample=SAMPLES),
        "qc/multiqc_reads.html",
        "qc/multiqc_alignments.html"
